name: zizmor

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"

concurrency:
  group: "zizmor-${{ github.ref }}"
  cancel-in-progress: false

permissions: {}

jobs:
  zizmor:
    name: Analyze
    permissions:
      contents: read
      security-events: write # required to upload SARIF results
    uses: starhaven-io/.github/.github/workflows/reusable-zizmor.yml@08b3f1b4ce2fbca8584ba854432b63a5160cd489 # v2026.07.05
